from setuptools import setup, find_packages

setup(
    name="sam-3d-body",
    version="1.0.0",
    author="Meta AI Research",
    description="Promptable model for single-image full-body 3D human mesh recovery",
    url="https://github.com/facebookresearch/sam-3d-body",
    packages=find_packages(),  # ← Remove where parameter
    # Remove package_dir entirely
    python_requires=">=3.10",
    install_requires=[
        "pytorch-lightning",
        "pyrender",
        "opencv-python",
        "yacs",
        "scikit-image",
        "einops",
        "timm",
        "dill",
        "pandas",
        "rich",
        "hydra-core",
        "hydra-submitit-launcher",
        "hydra-colorlog",
        "pyrootutils",
        "webdataset",
        "chump",
        "networkx==3.2.1",
        "roma",
        "joblib",
        "seaborn",
        "wandb",
        "appdirs",
        "appnope",
        "ffmpeg-python",
        "cython",
        "jsonlines",
        "pytest",
        # "xtcocotools",
        "loguru",
        "optree",
        "fvcore>=0.1.5",
        "black>=23.0.0",
        "pycocotools>=2.0.7",
        "tensorboard>=2.14.0",
        "huggingface-hub>=0.19.0",
        "supervision",
        "git+https://github.com/microsoft/MoGe.git@07444410f1e33f402353b99d6ccd26bd31e469e8"
    ],
)
